# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# The basics
add_newline = true

# Stuff
[character]
success_symbol = "[∑](bold green)"
error_symbol = "[χ](bold red)"


